### ISSUE TITLE
Output not on bottom of screen

### ISSUE THREAD

**Issue by comtronix** [justindomingue/ohSnap#11]
When using a large page with scrolldown, the output is not on the bottom of the screen.

**Comment by justindomingue** [comment]
Could you please give some steps to reproduce? I can't reproduce the issue on a large page.

**Comment by chadpriddle** [comment]
I'm having the sames issue. The error is at the bottom of the page but doesn't stick to the bottom as you scroll down, it just floats. I believe it's an issue with my own css within the app. Trying to find a way around it.

**Comment by justindomingue** [comment]
Is it solved? Can you post your CSS?
