### ISSUE TITLE
error and typo

### ISSUE THREAD

**Issue by hammel66** [justindomingue/ohSnap#15]
Hi!
First: There is a typing error in README.md in section **Usage** (o**s**Snap) which causes my first test to fail with an error...
```javascript
osSnap('Succefully created your account');
```
should be
```javascript
ohSnap('Succefully created your account');
```
Second: The is an error in the Javascript ohsnap.js (line 45)
First appearance of variable html without var.
My Test: I have called ohSnap(..) two times one after another and not all notifications faded out after five seconds because the variable html is global without var in front of.
With var there is one variable html for each call of ohSnap(..) which is used later in setTimeout(ohSnapX..).

```javascript
// Generate the HTML
html = $('<div class="alert ' + color_markup + '">' + icon_markup + text + '</div>').fadeIn(options['fade-duration']);
```
should be
```javascript
// Generate the HTML
var html = $('<div class="alert ' + color_markup + '">' + icon_markup + text + '</div>').fadeIn(options['fade-duration']);
```

Best
Martin

Sorry for my bad english!

**Comment by justindomingue** [comment]
Thanks for that! I just pushed a fix.
