### ISSUE TITLE
Option to change the ".alert" class

### ISSUE THREAD

**Issue by deflox** [justindomingue/ohSnap#18]
As far as I can see there's no option to change the default ".alert" class for a single message. 

It would be useful to add an option to modify this class, since I'm actually working with bootstrap and customization of the ".alert" class also overrides the bootstrap alert boxes styling. 

I would make the ".alert" class the default option if the user does not define the class.

**Comment by graddus-corp** [comment]
@deflox I changed the plugin code to modify the alert class as default. My code:

`function ohSnap(text, options) {
    var defaultOptions = {
        'color'       : null,     // color is  CSS class `alert-color`
        'icon'        : null,     // class of the icon to show before the alert text
        'duration'    : '5000',   // duration of the notification in ms
        'container-id': 'ohsnap', // id of the alert container
        'fade-duration': 'fast',  // duration of the fade in/out of the alerts. fast, slow or integer in ms
        'alert-class': 'snap'
    }

    options = (typeof options == 'object') ? $.extend(defaultOptions, options) : defaultOptions;

    var $container = $('#'+options['container-id']),
        icon_markup = "",
        color_markup = "",
        alert_class = "";

    if (options.icon) {
        icon_markup = "<span class='" + options.icon + "'></span> ";
    }

    if(options['alert-class']) {
        alert_class = options['alert-class'];
    }

    if (options.color) {
        color_markup = alert_class + '-' + options.color;
    }

    // Generate the HTML
    var html = $('<div class="'+alert_class + ' ' + color_markup + '">' + icon_markup + text + '</div>').fadeIn(options['fade-duration']);

    // Append the label to the container
    $container.append(html);

    // Remove the notification on click
    html.on('click', function() {
        ohSnapX($(this));
    });

    // After 'duration' seconds, the animation fades out
    setTimeout(function() {
        ohSnapX(html);
    }, options.duration);
}

/* Removes a toast from the page
 * params:
 *    Called without arguments, the function removes all alerts
 *    element: a jQuery object to remove
 *    options:
 *      duration: duration of the alert fade out - 'fast', 'slow' or time in ms. Default 'fast'
 */
function ohSnapX(element, options) {
    defaultOptions = {
        'duration': 'fast'
    }

    options = (typeof options == 'object') ? $.extend(defaultOptions, options) : defaultOptions;

    if (typeof element !== "undefined") {
        element.fadeOut(options.duration, function() {
            $(this).remove();
        });
    } else {
        $('.'+alert_class).fadeOut(options.duration, function() {
            $(this).remove();
        });
    }
}`

**Comment by mdennisa** [comment]
@deflox I have the same problem working with custom alert classname since its conflicting with bootstrap 4.

I forked and make some adjustment along with css example here https://github.com/mdennisa/ohSnap

**Comment by deflox** [comment]
Thanks! I will take a look at it.
